version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: akademus-postgres-dev
    restart: unless-stopped
    env_file:
      - .env.development
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      # Persist data between container restarts
      - postgres_data:/var/lib/postgresql/data
      # Optional: Custom initialization scripts
      - ./prisma/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - akademus-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: akademus-api-dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      PORT: ${PORT}
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      # Mount source code for development (hot reload)
      - ./src:/app/src
      - ./prisma:/app/prisma
      # Mount .env file for runtime configuration
      - ./.env.development:/app/.env.development
    networks:
      - akademus-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
    name: akademus-postgres-data

networks:
  akademus-network:
    name: akademus-dev-network
    driver: bridge
